name: Compliance check

on:
  workflow_call:  
    inputs:
      config-path:
        required: true
        type: string
env:
  applicationfolder: core



jobs:
  configure:
      - name: Print the input name to STDOUT
        run: echo $1 The username is 
        args:
            - ${{ inputs.config-path }}
