name: "Prowler Check"
description: "Run Prowler compliance checks"
inputs:
  aws-region:
    description: "AWS region"
    required: true
  config-file:
    description: "Path to the configuration file"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "${{ inputs.config-file }}"
      shell: bash
    - name: Install Prowler
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install prowler
      shell: bash
