name: Compliance check

on:
  workflow_call:  
    inputs:
      config-path:
        required: true
        description: "My image tag"
        default: "11"
        type: string
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
     - name: Checkout to repository
       uses: actions/checkout@v3
     - name: Set matrix data
       id: set-matrix
       run: echo "matrix=$(jq -c . < ${{ inputs.config-path }})" >> $GITHUB_OUTPUT
  Check:
    needs: configure
    name: Build and Package
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}    
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - name: Install Prowler
        run: |
            pip install prowler
            prowler -v

      - name: Run Prowler checks
        run: |
            prowler aws --compliance ${{ matrix.compliance }} --excluded-services ${{ matrix.exclude }}

      - name: Message
        run: |
            echo "Prowler run completed"
