name: Compliance check

on:
  workflow_call:  
    inputs:
      config-path:
        required: true
        description: "My image tag"
        default: "11"
        type: string
env:
  applicationfolder: core



jobs:
  configure:
     runs-on: ubuntu-latest
     steps:
      - name: Print the input name to STDOUT  
        run: echo ${{ inputs.config-path }} The username is 

